---
- name: Install global foreman
  sudo: yes
  shell:
    chruby-exec ruby-{{ ruby_version }} -- gem install foreman
    creates=/opt/rubies/ruby-{{ ruby_version }}/bin/foreman

- name: Install global foreman initd generator
  sudo: yes
  shell:
    chruby-exec ruby-{{ ruby_version }} -- gem install foreman-export-initscript

- name: disable service if exists
  sudo: yes
  service: name={{ app }} state=stopped enabled=no
  ignore_errors: yes

- name: bundle install
  shell:
    chruby-exec ruby-{{ ruby_version }} -- bundle install --without development:test
    chdir=/home/{{ ansible_ssh_user }}/www/{{ app }}/public

- name: set Procfile
  lineinfile:
    dest=/home/{{ ansible_ssh_user }}/www/{{ app }}/public/Procfile
    regexp="^web"
    line="web{{':'}} bundle exec puma -e production -t 1:16 -w {{ processors.stdout }} -b unix{{':'}}///tmp/{{ app }}.sock"
    backrefs=yes
    state=present

- name: upload env
  copy:
    src={{ local }}/.env
    dest=/home/{{ ansible_ssh_user }}/www/{{ app }}/public/.env
    force=yes

- name: set database env
  lineinfile:
    dest=/home/{{ ansible_ssh_user }}/www/{{ app }}/public/.env
    regexp="^DATABASE_URL"
    line='DATABASE_URL="postgres{{ ':' }}//{{ ansible_ssh_user }}{{ ':' }}{{ db_password}}@localhost/{{ app }}"'
    insertbefore=BOF
    state=present

- name: upgrade DB
  shell:
    chruby-exec ruby-{{ ruby_version }} -- bundle exec foreman run rake db:upgrade
    chdir=/home/{{ ansible_ssh_user }}/www/{{ app }}/public

- name: generate app initd daemon
  sudo: yes
  shell:
    chruby-exec ruby-{{ ruby_version }} -- foreman export initscript /etc/init.d -a {{ app }} -u {{ ansible_ssh_user }}
    chdir=/home/{{ ansible_ssh_user }}/www/{{ app }}/public

- name: set permissions for initd daemon
  sudo: yes
  file:
    path=/etc/init.d/{{ app }}
    mode=0755

- name: enable app service
  sudo: yes
  service: name={{ app }} state=started enabled=yes
