---

- name: install dependencies
  sudo: yes
  apt: name={{ item }} state=latest
  with_items:
    - gcc
    - make
    - libssl-dev
    - zlib1g-dev
    - e2fslibs-dev

- name: download
  get_url:
    url="https://www.tarsnap.com/download/tarsnap-autoconf-1.0.35.tgz"
    dest=/home/{{ ansible_ssh_user }}/tarsnap.tgz

- name: unpack
  unarchive:
    src=/home/{{ ansible_ssh_user }}/tarsnap.tgz
    dest=/home/{{ ansible_ssh_user }}/
    copy=no
    creates=/home/{{ ansible_ssh_user }}/tarsnap-autoconf-1.0.35/configure

- name: configure
  sudo: yes
  command:
    ./configure
    chdir=/home/{{ ansible_ssh_user }}/tarsnap-autoconf-1.0.35/
    creates=/home/{{ ansible_ssh_user }}/tarsnap-autoconf-1.0.35/config.h

- name: make
  sudo: yes
  command:
    make all install clean
    chdir=/home/{{ ansible_ssh_user }}/tarsnap-autoconf-1.0.35/
    creates=/usr/local/bin/tarsnap

- name: copy key
  sudo: yes
  copy:
    src=tarsnap_keys/{{ hostname }}.key
    dest=/root/.tarsnap.key
    mode=0600

- name: copy config file
  sudo: yes
  template:
    src=tarsnaprc.j2
    dest=/root/.tarsnaprc

- name: copy folders file
  sudo: yes
  template:
    src=tarsnap_folders.j2
    dest=/root/.tarsnap_folders

- name: create bin folder
  sudo: yes
  file: path=/root/bin state=directory

- name: copy tarsnap backups generator
  sudo: yes
  template:
    src=tarsnap-generations.j2
    dest=/root/bin/tarsnap-generations.sh
    mode=0700

- name: copy backup
  sudo: yes
  template:
    src=backup.j2
    dest=/root/bin/backup.sh
    mode=0700

- name: add cron entry
  sudo: yes
  cron:
    name="backup to tarsnap"
    user="root"
    minute="15"
    job="/root/bin/backup.sh >> /var/log/backup.log 2>&1"
    state=present
