---

- name: set newrelic repo key
  sudo: yes
  apt_key:
    url: https://download.newrelic.com/548C16BF.gpg
    id: 548C16BF
    state: present

- name: add newrelic repo
  sudo: yes
  apt_repository:
    repo='deb http://apt.newrelic.com/debian/ newrelic non-free'
    state=present

- name: update sources
  sudo: yes
  apt: update_cache=yes

- name: install newrelic
  sudo: yes
  apt: name={{ item }} state=latest
  with_items:
    - newrelic-sysmond

- name: set license key
  sudo: yes
  lineinfile:
    dest=/etc/newrelic/nrsysmond.cfg
    regexp="^license_key"
    line="license_key={{ newrelic_key }}"
    backrefs=yes
    state=present
  notify:
    - start newrelic
