---
- name: install common package
  sudo: yes
  apt: name={{ item }} state=latest
  with_items:
    - software-properties-common

- name: add brightbox repo
  sudo: yes
  apt_repository:
    repo='ppa:brightbox/ruby-ng'
    state=present

- name: update sources
  sudo: yes
  apt: update_cache=yes

- name: install ruby
  sudo: yes
  apt: name={{ item }} state=latest
  with_items:
    - ruby{{ version }}
    # - ruby-switch

- name: upload .gemrc
  template: src=gemrc.j2 dest=/home/{{ ansible_ssh_user }}/.gemrc

- name: install base gems
  sudo: yes
  apt: name={{ item }} state=latest
  with_items:
    - bundler
    - rake
