---
- name: install common package
  sudo: yes
  apt: name={{ item }} state=latest
  with_items:
    - software-properties-common
    - build-essential
    - libssl-dev

- name: add brightbox repo
  sudo: yes
  apt_repository:
    repo='ppa:brightbox/ruby-ng'
    state=present

- name: update sources
  sudo: yes
  apt: update_cache=yes

- name: install ruby
  sudo: yes
  apt: name={{ item }} state=latest
  with_items:
    - ruby{{ version }}
    - ruby{{ version }}-dev

- name: upload .gemrc
  template: src=gemrc.j2 dest=/home/{{ ansible_ssh_user }}/.gemrc

- name: install bundler
  sudo: yes
  shell:
    gem install bundler
    creates=/usr/local/bin/bundle
